### ISSUE TITLE
リポジトリを public にする

### ISSUE THREAD

**Issue by watiko** [bibliotheca-app/bibliotheca-pwa#28]
- [x] README.md の修正
- [x] トークンとかが commit に混入していないかチェック
- [x] CI の設定で第三者がトークンを確認できないことをチェック
- [x] ライセンス・利用規約周りを確認しておく
  - 依存関係
  - 使用している API
  - etc...

**Comment by watiko** [comment]
制限事項も書いておかないといけないかも
- 環境依存な設定をベタで書いている部分(firestore.rule とか firebase.config とか)
- firestore では全文検索できないので一旦データ件数 * 使用人数が多くないと仮定しているとか

**Comment by watiko** [comment]
- [ ] README にビルド手順などを追記
openbd は紹介ということで行けないだろうか。

**Comment by watiko** [comment]
https://github.com/ben-eb/caniuse-lite
CC BY 4.0 license

**Comment by sisisin** [comment]
`caniuse` , `spdx-exceptions` がCCライセンスだったけどどちらもビルド時に利用するだけでサイト上で配布するコードにbundleしていないのでOKと判断
